permalink: /:year/:month/:day/:title.html
auto: true
markdown: rdiscount
author: peterhost
title: peterhost
keywords: Programming, Tutorials, Git, Linux, PHP, Mysql, Postgresql, javascript
url: http://barkingcode.peterhost.fr
paginate: 6
